theme: jekyll-theme-merlot
# Site settings
title: BY Blog
SEOTitle: renaissance的博客 | BY Blog
header-img: img/post-bg-desk.jpg
email: ZDxxiaoran@gmail.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, renaissance的博客,   xuguozhu, C++,Qt,python,java,vue.js"
url: "http://health.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/MagicXran/health.github.io.git" # you code repository
